import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { ModeToggle } from "@/components/mode-toggle";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<>
			<html lang="pt-br" suppressHydrationWarning>
				<head />
				<body>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<SidebarProvider>
							<AppSidebar />
							<SidebarInset>
								<header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
									<div className="flex items-center gap-2 px-4">
										<SidebarTrigger className="-ml-1" />
										<Separator
											orientation="vertical"
											className="mr-2 data-[orientation=vertical]:h-4"
										/>
										<ModeToggle />
									</div>
								</header>
								<div className="flex flex-1 flex-col gap-4 p-4 pt-0">
									<div className="grid auto-rows-min gap-4 md:grid-cols-3">
										<div className="aspect-video rounded-xl bg-foreground/30" />
										<div className="aspect-video rounded-xl bg-foreground/30" />
										<div className="aspect-video rounded-xl bg-foreground/30" />
									</div>
									<div className="min-h-[100vh] flex-1 rounded-xl bg-foreground/30 md:min-h-min" />
								</div>

								<main>{children}</main>
							</SidebarInset>
						</SidebarProvider>
					</ThemeProvider>
				</body>
			</html>
		</>
	);
}
